name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Extract version from tag
      shell: powershell
      run: |
        $version = "${{ github.ref }}" -replace "refs/tags/v", ""
        echo "VERSION=$version" >> $env:GITHUB_ENV
        
    - name: Build application
      shell: powershell
      run: |
        .\build_clean.ps1 -Version "$env:VERSION" -OutputPath ".\release"
        
    - name: Create release archive
      shell: powershell
      run: |
        Compress-Archive -Path ".\release\*" -DestinationPath "POSPrinter_v$env:VERSION.zip" -Force
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: POSPrinter_v${{ env.VERSION }}.zip
        generate_release_notes: true
        name: POS Printer v${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
